### ISSUE TITLE
Error with JSON-RPC Callchedan

### ISSUE THREAD

**Issue by Bomf** [Alex7Kom/storekeeper#1]
hey, nice work with the storekeeper!
I have a question.
My storekeeper is running and i am using you challchedan library.
But when i open the example storehouse.php it tells me: 

{"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"Invalid Request"}}

Why is that?

**Comment by Alex7Kom** [comment]
You are not supposed to access `storehouse.php` directly, this script handles JSON-RPC requests from Storekeeper. When you try to access it directly, your web browser generates blank request which is invalid by JSON-RPC standard.
Both Storekeeper and `storehouse.php` act as a JSON-RPC server when receiving a request and as a JSON-RPC client when making a request.
If you have further questions please read about JSON-RPC first https://en.wikipedia.org/wiki/JSON-RPC
Note that `storehouse.php` is just an example and you can separate the server and the client in your application if you want.
